version: '3'
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
volumes:
  mongo_data:
